In [1]:
x = int(input("숫자를 입력해 주세요: "))
if x%2==0:
    print("입력된 수 : %d ==> 짝수"%x)
else:
    print("입력된 수 : %d ==> 홀수"%x)

숫자를 입력해 주세요: 1215
입력된 수 : 1215 ==> 홀수


In [14]:
x = int(input("성적을 입력해 주세요: "))
grades = {'A':90, 'B':80, 'C':70, 'D':0}
if x>100 or x<0:
    print("성적 입력 오류")
else:
    for grade, score in grades.items():
        if x >= score:
            print("성적: %d 는 %s 등급 입니다."%(x, grade))
            break

성적을 입력해 주세요: 120
성적 입력 오류


In [35]:
import datetime
this_year = datetime.datetime.now().year
datas = {1:{"연도":1900,"성별":"남성"},
        2:{"연도":1900,"성별":"여성"},
        3:{"연도":2000,"성별":"남성"},
        4:{"연도":2000,"성별":"여성"}}

jm = input("주민번호 :").replace("-","")
if len(jm)==13:
    G = int(jm[6])
    if G in datas.keys():
        year = int(jm[:2])
        month = int(jm[2:4])
        day = int(jm[4:6])
        birth_year = datas[G]["연도"]+year
        age = this_year - birth_year
        print("%d년 %02d월 %02d일, %d세, %s"%(birth_year,month,day,age,datas[G]["성별"]))
else:
    print("주민번호 입력 오류")

주민번호 :080111-4311256
2008년 01월 11일, 13세, 여성


In [47]:
class empDetails:
    def __init__(self,name,sal):
        self.name=name
        self.sal=sal
    @classmethod
    def increment(cls,name,none):
        return cls('yarramsetti',6000 + 500)
    @staticmethod
    def salChecking(sal):
        return sal > 6000

emp1=empDetails('durga prasad',6000)
emp2=empDetails.increment('yarramsetti',100)
# output is 'durga prasad'
print(emp1.name)
# output put is 6000
print(emp1.sal)
# output is 6500,because it change the sal variable
print(emp2.sal)
# output is 'yarramsetti' it change the state of name variable
print(emp2.name)
# output is True, because ,it change the state of sal variable
print(empDetails.salChecking(6500))

durga prasad
6000
6500
yarramsetti
True


# 실습문제 : 커피 자동머신

In [56]:
menu = """
[커피 자동주문 머신 메뉴]
-----------------------------
- 아메리카노는 2500원
- 카페라떼는 3000원
- 카푸치노는 3000원
입니다. 원하시는 커피종류와
잔수를 입력하세요.
-----------------------------
"""
coffee1 = int(input(menu+"아메리카노 몇잔?: "))
coffee2 = int(input("카페라떼 몇잔?: "))
coffee3 = int(input("아메리카노 몇잔?: "))
money_to_pay = coffee1*2500 +coffee2*3000+coffee3*3000
print("지불할 금액은 %d원입니다."%money_to_pay)
money = int(input("돈을 넣어주세요:"))
if money >= money_to_pay:
    print(f"거스름돈은 {money-money_to_pay} 원 입니다")
else:
    print(f"금액이 부족합니다.{money_to_pay-money} 원을 더 넣어주세요")


[커피 자동주문 머신 메뉴]
-----------------------------
- 아메리카노는 2500원
- 카페라떼는 3000원
- 카푸치노는 3000원
입니다. 원하시는 커피종류와
잔수를 입력하세요.
-----------------------------
아메리카노 몇잔?: 10
카페라떼 몇잔?: 5
아메리카노 몇잔?: 17
지불할 금액은 91000원입니다.
돈을 넣어주세요:50000
금액이 부족합니다.41000 원을 더 넣어주세요


# 난수 : random

In [57]:
import random

In [224]:
a_num = random.randint(1,6)
b_num = random.randint(1,6)

if a_num>b_num:
    winner="A"
elif a_num<b_num:
    winner="B"
else:
    winner="모두"
    
msg = """주사위를 던집니다!
----------------------------
A의 주사위 숫자는 %d입니다.
B의 주사위 숫자는 %d입니다.
----------------------------
%s가 이겼습니다.
"""%(a_num, b_num,winner)
print(msg)

주사위를 던집니다!
----------------------------
A의 주사위 숫자는 4입니다.
B의 주사위 숫자는 4입니다.
----------------------------
모두가 이겼습니다.



In [5]:
num = int(input("합계를 구할 숫자 입력 : "))
hap = sum([i for i in range(1,num+1)])
print(f"1~{num}까지의 합은: {hap}")

합계를 구할 숫자 입력 : 100
1~100까지의 합은: 5050


In [7]:
num = int(input("합계를 구할 숫자 입력 : "))
hap = sum([i for i in range(1,num+1) if i%2 !=0])
print(f"1~{num}까지의 합은: {hap}")

합계를 구할 숫자 입력 : 100
1~100까지의 합은: 2500


In [8]:
num = int(input("합계를 구할 숫자 입력 : "))
hap = sum([i for i in range(1,num+1) if i%3 !=0])
print(f"1~{num}까지의 합은: {hap}")

합계를 구할 숫자 입력 : 100
1~100까지의 합은: 3367


In [1]:
hor = int(input("몇 단까지 출력할까요?: "))
ver = int(input("몇 열 씩을 출력할까요?: "))
for j in range(2,hor+1):
    print(f"  #  {j:^5} 단", end="  ")
print()
for i in range(1,ver+1):
    for j in range(2,hor+1):
        print(f"{j:2} x {i:2} = {j*i:3}", end="  ")
    print()

몇 단까지 출력할까요?: 9
몇 열 씩을 출력할까요?: 9
  #    2   단    #    3   단    #    4   단    #    5   단    #    6   단    #    7   단    #    8   단    #    9   단  
 2 x  1 =   2   3 x  1 =   3   4 x  1 =   4   5 x  1 =   5   6 x  1 =   6   7 x  1 =   7   8 x  1 =   8   9 x  1 =   9  
 2 x  2 =   4   3 x  2 =   6   4 x  2 =   8   5 x  2 =  10   6 x  2 =  12   7 x  2 =  14   8 x  2 =  16   9 x  2 =  18  
 2 x  3 =   6   3 x  3 =   9   4 x  3 =  12   5 x  3 =  15   6 x  3 =  18   7 x  3 =  21   8 x  3 =  24   9 x  3 =  27  
 2 x  4 =   8   3 x  4 =  12   4 x  4 =  16   5 x  4 =  20   6 x  4 =  24   7 x  4 =  28   8 x  4 =  32   9 x  4 =  36  
 2 x  5 =  10   3 x  5 =  15   4 x  5 =  20   5 x  5 =  25   6 x  5 =  30   7 x  5 =  35   8 x  5 =  40   9 x  5 =  45  
 2 x  6 =  12   3 x  6 =  18   4 x  6 =  24   5 x  6 =  30   6 x  6 =  36   7 x  6 =  42   8 x  6 =  48   9 x  6 =  54  
 2 x  7 =  14   3 x  7 =  21   4 x  7 =  28   5 x  7 =  35   6 x  7 =  42   7 x  7 =  49   8 x  7 =  56   9 x  7 =  63  
 2 x  8

In [30]:
%%time
from numba import jit
import numpy as np

x = np.arange(10000)

# @jit(nopython=True) # Set "nopython" mode for best performance, equivalent to @njit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0
    for i in range(a.shape[0]):   # Numba likes loops
        # trace += np.tanh(a[i, i]) # Numba likes NumPy functions
        trace += i # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))

[49995000 49995001 49995002 ... 50004997 50004998 50004999]
Wall time: 0 ns


In [28]:
%%time
from numba import jit
import numpy as np

x = np.arange(10000).reshape(100, 100)

# @jit(nopython=True) # Set "nopython" mode for best performance, equivalent to @njit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0
    for i in range(a.shape[0]):   # Numba likes loops
        # trace += np.tanh(a[i, i]) # Numba likes NumPy functions
        trace += a[i, i] # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))

[[499950 499951 499952 ... 500047 500048 500049]
 [500050 500051 500052 ... 500147 500148 500149]
 [500150 500151 500152 ... 500247 500248 500249]
 ...
 [509650 509651 509652 ... 509747 509748 509749]
 [509750 509751 509752 ... 509847 509848 509849]
 [509850 509851 509852 ... 509947 509948 509949]]
Wall time: 997 µs
