In [1]:
import numpy as np
np.__version__

'1.21.2'

In [13]:
arr = np.array(range(10), dtype=np.int64)

In [14]:
type(arr), arr

(numpy.ndarray, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

In [17]:
k = arr.reshape(2,-1)*10

In [18]:
k.ndim

2

In [19]:
k.shape

(2, 5)

In [22]:
aa = ['aaaaaaa',1]
n_c = np.array(aa)
n_c

array(['aaaaaaa', '1'], dtype='<U11')

In [32]:
np.finfo('float16')

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [3]:
import numpy as np
x = np.array(range(1, 21))
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [6]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [12]:
x[(x%3==0) & (x%4==1)]

array([9])

In [14]:
hist, bins = np.histogram(x)
print(hist)
print(bins)

[2 2 2 2 2 2 2 2 2 2]
[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1 20. ]


In [15]:
help(np.histogram)

Help on function histogram in module numpy:

histogram(a, bins=10, range=None, normed=None, weights=None, density=None)
    Compute the histogram of a dataset.
    
    Parameters
    ----------
    a : array_like
        Input data. The histogram is computed over the flattened array.
    bins : int or sequence of scalars or str, optional
        If `bins` is an int, it defines the number of equal-width
        bins in the given range (10, by default). If `bins` is a
        sequence, it defines a monotonically increasing array of bin edges,
        including the rightmost edge, allowing for non-uniform bin widths.
    
        .. versionadded:: 1.11.0
    
        If `bins` is a string, it defines the method used to calculate the
        optimal bin width, as defined by `histogram_bin_edges`.
    
    range : (float, float), optional
        The lower and upper range of the bins.  If not provided, range
        is simply ``(a.min(), a.max())``.  Values outside the range are
        ig